<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LexFlow.Core\LexFlow.Core.csproj" />
    <ProjectReference Include="..\LexFlow.Storage\LexFlow.Storage.csproj" />
    <ProjectReference Include="..\LexFlow.Profiles\LexFlow.Profiles.csproj" />
  </ItemGroup>

</Project>
